# Generated by Django 4.1.1 on 2022-09-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='date_created',
        ),
    ]
